### ISSUE TITLE
Fix markup conversion error

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#1]
There are various errors in converting Jira markup to Markdown.

For example:
- tables are broken (looks like fixed in https://github.com/apache/lucene-jira-archive/commit/71b459540aaaae834301c6d44477efa90d04bad7 ?)
- [x] numbered lists converted to headers #19 
- [x] bullet lists are not converted #19
- [x] indents around quotes are not preserved #20
- [x] images are not properly shown in comments area even if the source URL is correct
- [x] jira's emoji is not converted to proper Unicode character
- [x] inline `{{monospaced}}` leave unnecessary bracket `{}` #21 
  - Looks like this is not a converter's bug. Actually, the original text contains extra brackets for some reason. Jira frontend leniently handles such error markup. 
  - e.g. `{{{}TermsEnum{}}}`

This issue tries to figure out the root cause of the errors and fix those.

**Comment by dweiss** [comment]
![image](https://user-images.githubusercontent.com/199470/176411524-9d1a8998-09cb-4544-9890-282ba1ff8b31.png)

This is what the bold block-issue looks like.

**Comment by mocobeta** [comment]
Thanks for reporting.

I found Jira's number list (`#`) is not correctly converted and it is interpreted as headers in Markdown. 

Jira dump
```
"body": "I'm definitely not an expert on this but after some research I found:\r\n # The real problem probably is we're assuming object alignment in 32 bit jvm is 4 bytes but they're actually default into 8 bytes in HotSpot JVM and can't be anything less than 8 bytes ([https://stackoverflow.com/questions/44468639/memory-alignment-of-java-classes)]\r\n # Object header may create offset for object alignment, like in your jol analysis, the header is 12 bytes long and thus created a 12%8=4 bytes offset, so that the target array size should cover those and that's why for {{byte[]}} 4,12,20... sizes are optimal, but I\u00a0*think* the header length can vary depend on either jvm or system, since I've seen some post with 2 mark words in the header which makes header 16 bytes\r\n\r\nSo there should be something we could optimize here, but probably need to figure out a way to identify how many bytes are in array header, ah [RamUsageEstimator|https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/RamUsageEstimator.java#L179,L187] listed the details out, the 64 bit machine's header is already aligned so we don't need to worry about the offset, and 32 bit machine's header is constant 12 bytes so with a 4 bytes offset.",
```

Converted markdown data
```
"body": "I'm definitely not an expert on this but after some research I found:\r\n # The real problem probably is we're assuming object alignment in 32 bit jvm is 4 bytes but they're actually default into 8 bytes in HotSpot JVM and can't be anything less than 8 bytes (<https://stackoverflow.com/questions/44468639/memory-alignment-of-java-classes)>\r\n # Object header may create offset for object alignment, like in your jol analysis, the header is 12 bytes long and thus created a 12%8=4 bytes offset, so that the target array size should cover those and that's why for `byte[]` 4,12,20... sizes are optimal, but I\u00a0**think** the header length can vary depend on either jvm or system, since I've seen some post with 2 mark words in the header which makes header 16 bytes\r\n\r\nSo there should be something we could optimize here, but probably need to figure out a way to identify how many bytes are in array header, ah [RamUsageEstimator](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/RamUsageEstimator.java#L179,L187) listed the details out, the 64 bit machine's header is already aligned so we don't need to worry about the offset, and 32 bit machine's header is constant 12 bytes so with a 4 bytes offset.\n\nAuthor: Patrick Zhai (`@zhaih`)\nCreated: 2022-06-09T07:07:05.021+0000\nUpdated: 2022-06-09T07:07:05.021+0000\n",
```

**Comment by mocobeta** [comment]
The conversion tool seems to erase consecutive LFs (`\n\n`); this causes indent errors n Markdown.

Removed LFs would be recovered by this regex (hack).

```
text = re.sub(r"\n\s*(?!\s*-)", "\n\n", text)
``` 

![Screenshot from 2022-07-01 01-45-47](https://user-images.githubusercontent.com/1825333/176733562-1835e865-a597-4b59-89c5-2b51d8e7baed.png)

**Comment by mikemccand** [comment]
> Looks like the converter library does not support Carriage Return `\r` and succeeding spaces after Line Feed `\n`

Sigh, will our species ever get past the different EOL characters/problems!!  Thanks for tracking this down @mocobeta.

**Comment by mocobeta** [comment]
Unfortunately, it was not so trivial. I forgot code blocks. In code blocs, spaces and line feed characters in the original text should be preserved and my solution breaks them.
I tried to deal with it with look-ahead and look-behind regex though, looks like it didn't help. I think it'd be not solvable with regular expression.

**Comment by mocobeta** [comment]
I think pre- or post- processing to tweak the converter's result is risky since any text processing required contexts (which block element the character sequence resides in - even LFs and spaces have special meanings in both Jira markup and Markdown).

**For your information**: I don't know how much effort we should/can invest in that though, maybe we would need a customized version of the converter tool if we want to safely fix conversion errors.
https://github.com/catcombo/jira2markdown
I haven't closely looked at it, but it's built upon [pyparsing](https://github.com/pyparsing/pyparsing/) (a well-known python parser generator library) and it already supports all Jira syntax; it'd be a good start.

**Comment by mocobeta** [comment]
I found at least one test issue in the test repo https://github.com/mocobeta/sandbox-lucene-10557/issues appears in google's top search result. I didn't think it happened so quickly, but I might have to make the repo private - if there is anyone who is interested in debugging this issue, please let me know. I'll give you access to the repo.

**Comment by mocobeta** [comment]
Made a tiny list of error examples in #12 that hopefully cover typical markup conversion errors.
Block elements (quote, bullet list, numbered list, and table) are sometimes correctly converted and sometimes broken depending on context. Haven't found the patterns.

**Comment by mikemccand** [comment]
> I found at least one test issue in the test repo https://github.com/mocobeta/sandbox-lucene-10557/issues appears in google's top search result. I didn't think it happens so quickly, but I might have to make the repo private. If there is anyone who is interested in reviewing/debugging this issue, please let me know. I'll give you access to the repo.

Hmm ... we could maybe rename the repository so that it [falls under one of the `robots.txt` rules at github.com](https://github.com/robots.txt)?  Reading at least one answer on stackoverflow suggested this approach.  Of course, it is brittle: if the `robots.txt` changes, the web crawlers will see the content again, but maybe for our short-term purposes it is acceptable?

Here's the current `robots.txt` content:

```
# If you would like to crawl GitHub contact us via https://support.github.com?tags=dotcom-robots
# We also provide an extensive API: https://docs.github.com
User-agent: baidu
crawl-delay: 1


User-agent: *

Disallow: /*/pulse
Disallow: /*/tree/
Disallow: /gist/
Disallow: /*/forks
Disallow: /*/stars
Disallow: /*/download
Disallow: /*/revisions
Disallow: /*/issues/new
Disallow: /*/issues/search
Disallow: /*/commits/
Disallow: /*/commits/*?author
Disallow: /*/commits/*?path
Disallow: /*/branches
Disallow: /*/tags
Disallow: /*/contributors
Disallow: /*/comments
Disallow: /*/stargazers
Disallow: /*/archive/
Disallow: /*/blame/
Disallow: /*/watchers
Disallow: /*/network
Disallow: /*/graphs
Disallow: /*/raw/
Disallow: /*/compare/
Disallow: /*/cache/
Disallow: /.git/
Disallow: */.git/
Disallow: /*.git$
Disallow: /search/advanced
Disallow: /search
Disallow: */search
Disallow: /*q=
Disallow: /*.atom

Disallow: /ekansa/Open-Context-Data
Disallow: /ekansa/opencontext-*
Disallow: */tarball/
Disallow: */zipball/

Disallow: /*source=*
Disallow: /*ref_cta=*
Disallow: /*plan=*
Disallow: /*return_to=*
Disallow: /*ref_loc=*
Disallow: /*setup_organization=*
Disallow: /*source_repo=*
Disallow: /*ref_page=*
Disallow: /*source=*
Disallow: /*referrer=*
Disallow: /*report=*
Disallow: /*author=*
Disallow: /*since=*
Disallow: /*until=*
Disallow: /*commits?author=*
Disallow: /*report-abuse?report=*
Disallow: /*tab=*
Allow: /*?tab=achievements&achievement=*

Disallow: /account-login
Disallow: /Explodingstuff/
```

So maybe if named/renamed this test repo with a prefix of `forks-` or `stars-`?  Of course, GitHub might disallow this, but it's worth a shot?

**Comment by mocobeta** [comment]
```
Disallow: /*/forks
```
I think the first wildcard `*` would match all repository names. It looks like this entry disallows crawling the forked repository list page? 

I made the test repo read-only ("archived") - at least nobody can update or add comments on that.
![Screenshot from 2022-07-04 21-17-47](https://user-images.githubusercontent.com/1825333/177153243-4afb9a0d-8d39-4bc8-aee1-cf546edb3635.png)

**Comment by mocobeta** [comment]
ah ok, `/*/forks` should match any path that includes "forks" after the second `/`. 
I'll change the repository name if it's needed; for now, there seems no substantial bad effect (we'd need to be careful not to increase the site rank of it).

**Comment by mocobeta** [comment]
I reviewed several hundreds of issues in the latest test migration. The conversion errors are not uncommon and readers would often have to go back to Jira to reach correct/original information - it's not a great experience. This is still a major blocker for migration to me.

**Comment by mocobeta** [comment]
I observed several conversion results with the recent changes. It looks like major flaws (broken tables/lists/quotes, unintentional header markups) have been fixed. There are still minor errors (1) (2) in nested/complex block elements - not sure how many such minor errors remain there or if they can be fixed in easy/safe ways.

(1) code block inside list is broken
![Screenshot from 2022-07-09 18-41-18](https://user-images.githubusercontent.com/1825333/178100398-d5602885-3f48-401f-9d95-44a864188469.png)

(2) mixed nested list (numberd/bullet) is broken
![Screenshot from 2022-07-09 18-43-58](https://user-images.githubusercontent.com/1825333/178100503-21ac1e66-cad2-4be9-9658-8a4d7a702f76.png)

**Comment by mocobeta** [comment]
Just a status update - I ran a full migration (on a private test repo) with the latest `main`, randomly picked issues from old to new, and checked if those are correctly converted to Markdown. Generally, it looks fine to me. And if there are glitches, readers now can quickly reach the original comment from the footer link thanks to #43.

With a few further small fixes, I'll run a full migration next week once again. It will hopefully be the final iteration, I'll make it publicly available to let others check/investigate the result.

**Comment by mikemccand** [comment]
Thanks @mocobeta -- the conversions are looking great -- I spot checked around a dozen issues yesterday.

Once you have the new full migration done, I suggest sending an email to the dev list to call everyone's attention to it, and set a time box (two or three days?).

**Comment by mikemccand** [comment]
I suggest also sending a separate email asking for people to state their GitHub id / Jira id mapping, if they are comfortable doing so?

Rather than having everyone make a PR / commit a change, I lower the barrier, maybe just allow them to reply to the email?  I volunteer to go through all replies and carry them over to the mapping file.

I still wonder/wish we could use Apache's LDAP server behind `id.apache.org` -- it sometimes knows the GitHub id of committers.  Hmm but I'm not sure if it knows the Jira id?  TooManyIDsException!!

**Comment by mocobeta** [comment]
> Rather than having everyone make a PR / commit a change, I lower the barrier, maybe just allow them to reply to the email? I volunteer to go through all replies and carry them over to the mapping file.

Thanks for your suggestion, I sent an e-mail to the dev list.

**Comment by mikemccand** [comment]
> GitHub won't accept labels such as `legacy-jira-label:java11` for some reason

That's really weird ;)

I was able to apply the label to [this issue](https://github.com/apache/lucene-jira-archive/issues/78) through the GitHub web UI.  Not sure why import API would fail on it!

**Comment by mocobeta** [comment]
Problems were fixed in #82 and #84. I restarted the rehearsal.

**Comment by mocobeta** [comment]
All issues (LUCENE-1 to LUCENE-10664) were successfully migrated into 
https://github.com/mocobeta/forks-migration-test/issues

I'll manually check if there are major conversion errors and if it looks fine, will open an INFRA issue.

**Comment by dweiss** [comment]
It is _really_ impressive what you've been able to achieve, @mocobeta !

I peeked at a few issues and noticed the following minor glitches:
* link conversion error?
![image](https://user-images.githubusercontent.com/199470/181890735-a5937161-9351-4166-b079-2822ff34f62a.png)
* link "mention" dates are from the import time - this isn't solvable, I think.
![image](https://user-images.githubusercontent.com/199470/181892992-03b40bd3-1fb1-4ec6-b95a-cca079e6d95a.png)
* Maybe it'd be better to move the original comment author up to the top of the converted comment? Otherwise, for long comments, it's hard to see who's replying.
![image](https://user-images.githubusercontent.com/199470/181894900-012d96b5-89ba-4104-90e2-923a15761fd6.png)
I'd move it to the top and make it "Legacy jira comment by ...".

**Comment by mocobeta** [comment]
> link conversion error?

Looks like the author nests the hyperlink syntax `[anchor|url]` in monospace `{{xxx}}` and bold text `*xxx*`. This seems to confuse the parser. I'd leave this because I think it'd be difficult to fix (we need to peek at how Jira handles such complex inline syntax nests), and hope such complex Jira syntax usage is rare.

Original Jira snippet:
```
*{{{}CompressingStoredFieldsWriter.{}}}{{{}copyOneDoc\u00a0[like|https://github.com/apache/lucene/blob/382962f22df3ee3af3fb538b877c98d61a622ddb/lucene/core/src/java/org/apache/lucene/codecs/lucene90/compressing/Lucene90CompressingStoredFieldsWriter.java#L516]\u00a0and CompressingTermVectorsWriter.flush{}}}*
```

**Comment by mocobeta** [comment]
> link "mention" dates are from the import time  - this isn't solvable, I think.

I don't think the github API user can control the timestamp of mentions.

**Comment by mocobeta** [comment]
> I'd move it to the top and make it "Legacy jira comment by ...".

I agree. This was fixed in #88.

**Comment by mocobeta** [comment]
I browsed through several issues and made a few small but important bug fixes.

@mikemccand I'll leave this test repo for one week or so for further review. If there are not any big concerns I plan to freeze the account mapping and scripts, then open an INFRA issue.
https://github.com/mocobeta/forks-migration-test/issues

**Comment by mikemccand** [comment]
> @mikemccand I'll leave this test repo for one week or so for further review. If there are not any big concerns I plan to freeze the account mapping and scripts, then open an INFRA issue

+1, thanks @mocobeta!  Please send a email to the dev list calling attention to this final testing phase?

**Comment by mocobeta** [comment]
I could bother the mail list though, I see little hope of gaining testers for such messy manual testing (everyone is busy at their own work). But please feel free to draw attention to this if you would like - maybe it'd be more effective.

**Comment by mikemccand** [comment]
> But please feel free to draw attention to this if you would like - maybe it'd be more effective.

OK I sent an email!:  https://lucene.markmail.org/thread/x3xndlwfaydwmq5v

**Comment by mocobeta** [comment]
Thank you for sending a call for help.

**Comment by mikemccand** [comment]
> Thank you for sending the call for help.

YW -- it's the least I could do!!

I will also send a call for help for users (not just devs) to record their jira id / GitHub id mapping.

In fact, we should more generally announce our planned schedule to java-user@ as well once we have a specific timeline planned.

**Comment by mocobeta** [comment]
> In fact, we should more generally announce our planned schedule to java-user@ as well once we have a specific timeline planned.

I will make an announcement about the detailed schedule to both dev@ java-user@ two or three days before the migration is started. Don't worry about it - I have become good at such administrative work whether I like it or not.

**Comment by mocobeta** [comment]
I'm closing this - known conversion errors will be adderessed in follow-up issues (if it's possible to fix).
